---

- name: Copy & uncompress files
  unarchive:
    src: /root/project/backend.zip
    dest: /home/ubuntu

# - name: Copy files to ec2
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Install npm packages
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Daemonize pm2
  become: true
  shell: |
    env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

- name: Build & run
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run start
    pm2 save

