---

- name: Copy & uncompress files
  unarchive:
    src: /root/project/backend.zip
    dest: /home/ubuntu

# - name: Copy files to ec2
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Install npm packages
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build & run
  become: true
  shell: |
    cd /home/ubuntu/backend
    rm -rf dist
    npm run build
    pm2 ls
    NODE_ENV=production pm2 start dist/main.js
