---

- name: Copy & uncompress files
  unarchive:
    src: /root/project/backend.zip
    dest: /home/ubuntu

# - name: Copy files to ec2
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Install npm packages
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Daemonize pm2
  become: true
  command: pm2 startup systemd -u username --hp /home/username
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Build & run
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run start
    pm2 save

